service: hotcities-lambdas

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  profile: hotcities-${self:provider.stage}
  environment:
    MONGO_CONNECTION: ${self:custom.secrets}.MONGO_CONNECTION
    OPENWEATHERMAP_KEY: ${self:custom.secrets}.OPENWEATHERMAP_KEY
    FLICKR_KEY: ${self:custom.secrets}.FLICKR_KEY
    TWITTER_CONSUMER_KEY: ${self:custom.secrets}.TWITTER_CONSUMER_KEY
    TWITTER_CONSUMER_SECRET: ${self:custom.secrets}.TWITTER_CONSUMER_SECRET
    TWITTER_ACCESS_TOKEN: ${self:custom.secrets}.TWITTER_ACCESS_TOKEN
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.secrets}.TWITTER_ACCESS_TOKEN_SECRET

functions:
  api:
    handler: src/handler.api
    events:
      - http:
          path: cities
          method: get
  fetcher:
    handler: src/handler.fetcher
    timeout: 60
    events:
      - schedule: cron(0/2 * * * ? *)
  recorder:
    handler: src/handler.recorder
    timeout: 60
    events:
      - schedule: cron(0/10 * * * ? *)
  twitterbot:
    handler: src/handler.twitterbot
    timeout: 60
    # events:
    #   - schedule: cron(0 * * * ? *)

custom:
  secrets: file(./serverless.env.yml):${self:provider.stage}
