service: hotcities-fetcher

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2

functions:
  fetcher:
    handler: handler.run
    events:
      - schedule: rate(10 minutes)
