service: hotcities-lambdas

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  accessKeyId: ${self:custom.secrets.AWS_KEY}
  secretAccessKey: ${self:custom.secrets.AWS_SECRET}
  environment:
    MONGO_CONNECTION: ${self:custom.secrets.MONGO_CONNECTION}
    OPENWEATHERMAP_KEY: ${self:custom.secrets.OPENWEATHERMAP_KEY}
    FLICKR_KEY: ${self:custom.secrets.FLICKR_KEY}
    TWITTER_CONSUMER_KEY: ${self:custom.secrets.TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${self:custom.secrets.TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${self:custom.secrets.TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.secrets.TWITTER_ACCESS_TOKEN_SECRET}

functions:
  server:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  fetcher:
    handler: src/fetcher.handler
    timeout: 60
    events:
      - schedule: cron(0/2 * * * ? *)
  recorder:
    handler: src/recorder.handler
    timeout: 60
    events:
      - schedule: cron(0/10 * * * ? *)
  twitterbot:
    handler: src/twitterbot.handler
    timeout: 60
    events:
      - schedule:
          rate: rate(60 minutes)

plugins:
  - serverless-offline

custom:
  secrets: ${file(./serverless.env.yml):${self:provider.stage}}
