service: hotcities-lambdas

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  environment:
    MONGO_CONNECTION: ${self:custom.secrets.MONGO_CONNECTION}
    OPENWEATHERMAP_KEY: ${self:custom.secrets.OPENWEATHERMAP_KEY}
    FLICKR_KEY: ${self:custom.secrets.FLICKR_KEY}
    TWITTER_CONSUMER_KEY: ${self:custom.secrets.TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${self:custom.secrets.TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${self:custom.secrets.TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.secrets.TWITTER_ACCESS_TOKEN_SECRET}

functions:
  server:
    handler: src/server.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
  fetcher:
    handler: src/fetcher.handler
    timeout: 60
    events:
      - rate: rate(2 minutes)
  recorder:
    handler: src/recorder.handler
    timeout: 60
    events:
      - rate: rate(10 minutes)
  twitterbot:
    handler: src/twitterbot.handler
    timeout: 60
    events:
      - schedule:
          rate: rate(60 minutes)

plugins:
  - serverless-offline
custom:
  secrets: ${file(./serverless.env.yml):${self:provider.stage}}
