service: hotcities-lambdas

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  profile: hotcities-dev
  environment:
    OPENWEATHERMAP_KEY: ${file(./serverless.env.yml):dev.OPENWEATHERMAP_KEY}
    MONGO_CONNECTION: ${file(./serverless.env.yml):dev.MONGO_CONNECTION}

functions:
  fetcher:
    handler: src/handler.fetcher
    timeout: 30
    events:
      - schedule: cron(0/1 * * * ? *)
  recorder:
    handler: src/handler.recorder
    timeout: 30
    events:
      - schedule: cron(0/10 * * * ? *)
