name: Deploy to prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Install Serverless Framework
        run: npm install -g serverless && serverless plugin install -n serverless-offline
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: eu-west-2
          profile-name: hotcities-prod
      - name: Create env file
        run: |
          cat > serverless.env.yml << EOF
          ${{ secrets.SLS_ENV }}
          EOF
      - name: Deploy to prod
        run: sls deploy --stage prod