name: Deploy to prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Install Serverless Framework
        run: |
          npm install -g serverless
          sls plugin install -n serverless-offline
      - name: Create env file
        run: |
          cat > serverless.env.yml << EOF
          ${{ secrets.SLS_ENV }}
          EOF
      - name: Deploy to prod
        run: sls deploy --stage prod